# Generated by Django 5.0 on 2023-12-05 21:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_cupomdesconto_alter_pedido_data_pedido_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cupom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedido.cupomdesconto'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 18, 27, 43, 725736)),
        ),
    ]
