# Generated by Django 4.2 on 2023-04-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('cidade', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('caracteristica_empresa', models.TextField()),
            ],
        ),
    ]
