# Generated by Django 5.0.3 on 2024-03-20 19:56

import django.db.models.deletion
import tinymce.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('status', models.CharField(choices=[('SO', 'Orçamento Solicitado'), ('EA', 'Em Análise'), ('R', 'Realizado'), ('C', 'Cancelado'), ('F', 'Fechado')], default='SO', max_length=2)),
                ('service_tag', models.CharField(choices=[('SO', 'Orçamento Solicitado'), ('EA', 'Em Análise'), ('R', 'Realizado'), ('C', 'Cancelado'), ('F', 'Fechado')], default='SO', max_length=2)),
                ('descricao', tinymce.models.HTMLField()),
                ('file_path', models.CharField(max_length=300)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
