# Generated by Django 4.2.2 on 2023-06-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0003_refeicao_opcao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidasPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('torax', models.IntegerField()),
                ('braco_relaxado', models.IntegerField()),
                ('braco_contraido', models.IntegerField()),
                ('cintura', models.IntegerField()),
                ('abdomen', models.IntegerField()),
                ('coxa', models.IntegerField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plataforma.pacientes')),
            ],
        ),
    ]
